/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoftphoneRouteImport } from './routes/softphone'
import { Route as AdminsRouteImport } from './routes/admins'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SoftphoneScenarioIdRouteImport } from './routes/softphone.$scenarioId'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AdminsUsersRouteImport } from './routes/admins.users'
import { Route as AdminsDeveloperInformationRouteImport } from './routes/admins.developer-information'
import { Route as AdminsAnalyticsRouteImport } from './routes/admins.analytics'
import { Route as AdminsScenariosIndexRouteImport } from './routes/admins.scenarios.index'
import { Route as ApiSoftphoneUnlockRouteImport } from './routes/api/softphone/unlock'
import { Route as ApiSoftphoneExternalEndpointsRouteImport } from './routes/api/softphone/external-endpoints'
import { Route as ApiSoftphoneEventsRouteImport } from './routes/api/softphone/events'
import { Route as ApiSoftphoneCaseRouteImport } from './routes/api/softphone/case'
import { Route as ApiSoftphoneBootstrapRouteImport } from './routes/api/softphone/bootstrap'
import { Route as ApiSoftphoneAcsTokenRouteImport } from './routes/api/softphone/acs-token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminsScenariosNewRouteImport } from './routes/admins.scenarios.new'
import { Route as AdminsScenariosScenarioIdRouteImport } from './routes/admins.scenarios.$scenarioId'
import { Route as ApiSoftphoneScenarioScenarioIdRouteImport } from './routes/api/softphone/scenario.$scenarioId'
import { Route as ApiSoftphoneCaseSetRouteImport } from './routes/api/softphone/case/set'
import { Route as ApiSoftphoneCaseIvrRecognizedRouteImport } from './routes/api/softphone/case/ivr-recognized'
import { Route as ApiSoftphoneCaseIvrRawTextRouteImport } from './routes/api/softphone/case/ivr-raw-text'
import { Route as ApiSoftphoneCaseDebugInformationRouteImport } from './routes/api/softphone/case/debug-information'
import { Route as ApiPublicSoftphoneCaseSetRouteImport } from './routes/api/public/softphone/case/set'
import { Route as ApiPublicSoftphoneCaseGetRouteImport } from './routes/api/public/softphone/case/get'
import { Route as ApiPublicSoftphoneCasePhaseSetRouteImport } from './routes/api/public/softphone/case/phase/set'
import { Route as ApiPublicSoftphoneCaseIvrRecognizedSetRouteImport } from './routes/api/public/softphone/case/ivr-recognized/set'
import { Route as ApiPublicSoftphoneCaseIvrRawTextSetRouteImport } from './routes/api/public/softphone/case/ivr-raw-text/set'
import { Route as ApiPublicSoftphoneCaseEventSetRouteImport } from './routes/api/public/softphone/case/event/set'
import { Route as ApiPublicSoftphoneCaseDebugInformationSetRouteImport } from './routes/api/public/softphone/case/debug-information/set'

const SoftphoneRoute = SoftphoneRouteImport.update({
  id: '/softphone',
  path: '/softphone',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsRoute = AdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftphoneScenarioIdRoute = SoftphoneScenarioIdRouteImport.update({
  id: '/$scenarioId',
  path: '/$scenarioId',
  getParentRoute: () => SoftphoneRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsUsersRoute = AdminsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminsRoute,
} as any)
const AdminsDeveloperInformationRoute =
  AdminsDeveloperInformationRouteImport.update({
    id: '/developer-information',
    path: '/developer-information',
    getParentRoute: () => AdminsRoute,
  } as any)
const AdminsAnalyticsRoute = AdminsAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminsRoute,
} as any)
const AdminsScenariosIndexRoute = AdminsScenariosIndexRouteImport.update({
  id: '/scenarios/',
  path: '/scenarios/',
  getParentRoute: () => AdminsRoute,
} as any)
const ApiSoftphoneUnlockRoute = ApiSoftphoneUnlockRouteImport.update({
  id: '/api/softphone/unlock',
  path: '/api/softphone/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSoftphoneExternalEndpointsRoute =
  ApiSoftphoneExternalEndpointsRouteImport.update({
    id: '/api/softphone/external-endpoints',
    path: '/api/softphone/external-endpoints',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSoftphoneEventsRoute = ApiSoftphoneEventsRouteImport.update({
  id: '/api/softphone/events',
  path: '/api/softphone/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSoftphoneCaseRoute = ApiSoftphoneCaseRouteImport.update({
  id: '/api/softphone/case',
  path: '/api/softphone/case',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSoftphoneBootstrapRoute = ApiSoftphoneBootstrapRouteImport.update({
  id: '/api/softphone/bootstrap',
  path: '/api/softphone/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSoftphoneAcsTokenRoute = ApiSoftphoneAcsTokenRouteImport.update({
  id: '/api/softphone/acs-token',
  path: '/api/softphone/acs-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsScenariosNewRoute = AdminsScenariosNewRouteImport.update({
  id: '/scenarios/new',
  path: '/scenarios/new',
  getParentRoute: () => AdminsRoute,
} as any)
const AdminsScenariosScenarioIdRoute =
  AdminsScenariosScenarioIdRouteImport.update({
    id: '/scenarios/$scenarioId',
    path: '/scenarios/$scenarioId',
    getParentRoute: () => AdminsRoute,
  } as any)
const ApiSoftphoneScenarioScenarioIdRoute =
  ApiSoftphoneScenarioScenarioIdRouteImport.update({
    id: '/api/softphone/scenario/$scenarioId',
    path: '/api/softphone/scenario/$scenarioId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSoftphoneCaseSetRoute = ApiSoftphoneCaseSetRouteImport.update({
  id: '/set',
  path: '/set',
  getParentRoute: () => ApiSoftphoneCaseRoute,
} as any)
const ApiSoftphoneCaseIvrRecognizedRoute =
  ApiSoftphoneCaseIvrRecognizedRouteImport.update({
    id: '/ivr-recognized',
    path: '/ivr-recognized',
    getParentRoute: () => ApiSoftphoneCaseRoute,
  } as any)
const ApiSoftphoneCaseIvrRawTextRoute =
  ApiSoftphoneCaseIvrRawTextRouteImport.update({
    id: '/ivr-raw-text',
    path: '/ivr-raw-text',
    getParentRoute: () => ApiSoftphoneCaseRoute,
  } as any)
const ApiSoftphoneCaseDebugInformationRoute =
  ApiSoftphoneCaseDebugInformationRouteImport.update({
    id: '/debug-information',
    path: '/debug-information',
    getParentRoute: () => ApiSoftphoneCaseRoute,
  } as any)
const ApiPublicSoftphoneCaseSetRoute =
  ApiPublicSoftphoneCaseSetRouteImport.update({
    id: '/api/public/softphone/case/set',
    path: '/api/public/softphone/case/set',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSoftphoneCaseGetRoute =
  ApiPublicSoftphoneCaseGetRouteImport.update({
    id: '/api/public/softphone/case/get',
    path: '/api/public/softphone/case/get',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSoftphoneCasePhaseSetRoute =
  ApiPublicSoftphoneCasePhaseSetRouteImport.update({
    id: '/api/public/softphone/case/phase/set',
    path: '/api/public/softphone/case/phase/set',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSoftphoneCaseIvrRecognizedSetRoute =
  ApiPublicSoftphoneCaseIvrRecognizedSetRouteImport.update({
    id: '/api/public/softphone/case/ivr-recognized/set',
    path: '/api/public/softphone/case/ivr-recognized/set',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSoftphoneCaseIvrRawTextSetRoute =
  ApiPublicSoftphoneCaseIvrRawTextSetRouteImport.update({
    id: '/api/public/softphone/case/ivr-raw-text/set',
    path: '/api/public/softphone/case/ivr-raw-text/set',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSoftphoneCaseEventSetRoute =
  ApiPublicSoftphoneCaseEventSetRouteImport.update({
    id: '/api/public/softphone/case/event/set',
    path: '/api/public/softphone/case/event/set',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSoftphoneCaseDebugInformationSetRoute =
  ApiPublicSoftphoneCaseDebugInformationSetRouteImport.update({
    id: '/api/public/softphone/case/debug-information/set',
    path: '/api/public/softphone/case/debug-information/set',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admins': typeof AdminsRouteWithChildren
  '/softphone': typeof SoftphoneRouteWithChildren
  '/admins/analytics': typeof AdminsAnalyticsRoute
  '/admins/developer-information': typeof AdminsDeveloperInformationRoute
  '/admins/users': typeof AdminsUsersRoute
  '/api/health': typeof ApiHealthRoute
  '/softphone/$scenarioId': typeof SoftphoneScenarioIdRoute
  '/admins/scenarios/$scenarioId': typeof AdminsScenariosScenarioIdRoute
  '/admins/scenarios/new': typeof AdminsScenariosNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/softphone/acs-token': typeof ApiSoftphoneAcsTokenRoute
  '/api/softphone/bootstrap': typeof ApiSoftphoneBootstrapRoute
  '/api/softphone/case': typeof ApiSoftphoneCaseRouteWithChildren
  '/api/softphone/events': typeof ApiSoftphoneEventsRoute
  '/api/softphone/external-endpoints': typeof ApiSoftphoneExternalEndpointsRoute
  '/api/softphone/unlock': typeof ApiSoftphoneUnlockRoute
  '/admins/scenarios/': typeof AdminsScenariosIndexRoute
  '/api/softphone/case/debug-information': typeof ApiSoftphoneCaseDebugInformationRoute
  '/api/softphone/case/ivr-raw-text': typeof ApiSoftphoneCaseIvrRawTextRoute
  '/api/softphone/case/ivr-recognized': typeof ApiSoftphoneCaseIvrRecognizedRoute
  '/api/softphone/case/set': typeof ApiSoftphoneCaseSetRoute
  '/api/softphone/scenario/$scenarioId': typeof ApiSoftphoneScenarioScenarioIdRoute
  '/api/public/softphone/case/get': typeof ApiPublicSoftphoneCaseGetRoute
  '/api/public/softphone/case/set': typeof ApiPublicSoftphoneCaseSetRoute
  '/api/public/softphone/case/debug-information/set': typeof ApiPublicSoftphoneCaseDebugInformationSetRoute
  '/api/public/softphone/case/event/set': typeof ApiPublicSoftphoneCaseEventSetRoute
  '/api/public/softphone/case/ivr-raw-text/set': typeof ApiPublicSoftphoneCaseIvrRawTextSetRoute
  '/api/public/softphone/case/ivr-recognized/set': typeof ApiPublicSoftphoneCaseIvrRecognizedSetRoute
  '/api/public/softphone/case/phase/set': typeof ApiPublicSoftphoneCasePhaseSetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admins': typeof AdminsRouteWithChildren
  '/softphone': typeof SoftphoneRouteWithChildren
  '/admins/analytics': typeof AdminsAnalyticsRoute
  '/admins/developer-information': typeof AdminsDeveloperInformationRoute
  '/admins/users': typeof AdminsUsersRoute
  '/api/health': typeof ApiHealthRoute
  '/softphone/$scenarioId': typeof SoftphoneScenarioIdRoute
  '/admins/scenarios/$scenarioId': typeof AdminsScenariosScenarioIdRoute
  '/admins/scenarios/new': typeof AdminsScenariosNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/softphone/acs-token': typeof ApiSoftphoneAcsTokenRoute
  '/api/softphone/bootstrap': typeof ApiSoftphoneBootstrapRoute
  '/api/softphone/case': typeof ApiSoftphoneCaseRouteWithChildren
  '/api/softphone/events': typeof ApiSoftphoneEventsRoute
  '/api/softphone/external-endpoints': typeof ApiSoftphoneExternalEndpointsRoute
  '/api/softphone/unlock': typeof ApiSoftphoneUnlockRoute
  '/admins/scenarios': typeof AdminsScenariosIndexRoute
  '/api/softphone/case/debug-information': typeof ApiSoftphoneCaseDebugInformationRoute
  '/api/softphone/case/ivr-raw-text': typeof ApiSoftphoneCaseIvrRawTextRoute
  '/api/softphone/case/ivr-recognized': typeof ApiSoftphoneCaseIvrRecognizedRoute
  '/api/softphone/case/set': typeof ApiSoftphoneCaseSetRoute
  '/api/softphone/scenario/$scenarioId': typeof ApiSoftphoneScenarioScenarioIdRoute
  '/api/public/softphone/case/get': typeof ApiPublicSoftphoneCaseGetRoute
  '/api/public/softphone/case/set': typeof ApiPublicSoftphoneCaseSetRoute
  '/api/public/softphone/case/debug-information/set': typeof ApiPublicSoftphoneCaseDebugInformationSetRoute
  '/api/public/softphone/case/event/set': typeof ApiPublicSoftphoneCaseEventSetRoute
  '/api/public/softphone/case/ivr-raw-text/set': typeof ApiPublicSoftphoneCaseIvrRawTextSetRoute
  '/api/public/softphone/case/ivr-recognized/set': typeof ApiPublicSoftphoneCaseIvrRecognizedSetRoute
  '/api/public/softphone/case/phase/set': typeof ApiPublicSoftphoneCasePhaseSetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admins': typeof AdminsRouteWithChildren
  '/softphone': typeof SoftphoneRouteWithChildren
  '/admins/analytics': typeof AdminsAnalyticsRoute
  '/admins/developer-information': typeof AdminsDeveloperInformationRoute
  '/admins/users': typeof AdminsUsersRoute
  '/api/health': typeof ApiHealthRoute
  '/softphone/$scenarioId': typeof SoftphoneScenarioIdRoute
  '/admins/scenarios/$scenarioId': typeof AdminsScenariosScenarioIdRoute
  '/admins/scenarios/new': typeof AdminsScenariosNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/softphone/acs-token': typeof ApiSoftphoneAcsTokenRoute
  '/api/softphone/bootstrap': typeof ApiSoftphoneBootstrapRoute
  '/api/softphone/case': typeof ApiSoftphoneCaseRouteWithChildren
  '/api/softphone/events': typeof ApiSoftphoneEventsRoute
  '/api/softphone/external-endpoints': typeof ApiSoftphoneExternalEndpointsRoute
  '/api/softphone/unlock': typeof ApiSoftphoneUnlockRoute
  '/admins/scenarios/': typeof AdminsScenariosIndexRoute
  '/api/softphone/case/debug-information': typeof ApiSoftphoneCaseDebugInformationRoute
  '/api/softphone/case/ivr-raw-text': typeof ApiSoftphoneCaseIvrRawTextRoute
  '/api/softphone/case/ivr-recognized': typeof ApiSoftphoneCaseIvrRecognizedRoute
  '/api/softphone/case/set': typeof ApiSoftphoneCaseSetRoute
  '/api/softphone/scenario/$scenarioId': typeof ApiSoftphoneScenarioScenarioIdRoute
  '/api/public/softphone/case/get': typeof ApiPublicSoftphoneCaseGetRoute
  '/api/public/softphone/case/set': typeof ApiPublicSoftphoneCaseSetRoute
  '/api/public/softphone/case/debug-information/set': typeof ApiPublicSoftphoneCaseDebugInformationSetRoute
  '/api/public/softphone/case/event/set': typeof ApiPublicSoftphoneCaseEventSetRoute
  '/api/public/softphone/case/ivr-raw-text/set': typeof ApiPublicSoftphoneCaseIvrRawTextSetRoute
  '/api/public/softphone/case/ivr-recognized/set': typeof ApiPublicSoftphoneCaseIvrRecognizedSetRoute
  '/api/public/softphone/case/phase/set': typeof ApiPublicSoftphoneCasePhaseSetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admins'
    | '/softphone'
    | '/admins/analytics'
    | '/admins/developer-information'
    | '/admins/users'
    | '/api/health'
    | '/softphone/$scenarioId'
    | '/admins/scenarios/$scenarioId'
    | '/admins/scenarios/new'
    | '/api/auth/$'
    | '/api/softphone/acs-token'
    | '/api/softphone/bootstrap'
    | '/api/softphone/case'
    | '/api/softphone/events'
    | '/api/softphone/external-endpoints'
    | '/api/softphone/unlock'
    | '/admins/scenarios/'
    | '/api/softphone/case/debug-information'
    | '/api/softphone/case/ivr-raw-text'
    | '/api/softphone/case/ivr-recognized'
    | '/api/softphone/case/set'
    | '/api/softphone/scenario/$scenarioId'
    | '/api/public/softphone/case/get'
    | '/api/public/softphone/case/set'
    | '/api/public/softphone/case/debug-information/set'
    | '/api/public/softphone/case/event/set'
    | '/api/public/softphone/case/ivr-raw-text/set'
    | '/api/public/softphone/case/ivr-recognized/set'
    | '/api/public/softphone/case/phase/set'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admins'
    | '/softphone'
    | '/admins/analytics'
    | '/admins/developer-information'
    | '/admins/users'
    | '/api/health'
    | '/softphone/$scenarioId'
    | '/admins/scenarios/$scenarioId'
    | '/admins/scenarios/new'
    | '/api/auth/$'
    | '/api/softphone/acs-token'
    | '/api/softphone/bootstrap'
    | '/api/softphone/case'
    | '/api/softphone/events'
    | '/api/softphone/external-endpoints'
    | '/api/softphone/unlock'
    | '/admins/scenarios'
    | '/api/softphone/case/debug-information'
    | '/api/softphone/case/ivr-raw-text'
    | '/api/softphone/case/ivr-recognized'
    | '/api/softphone/case/set'
    | '/api/softphone/scenario/$scenarioId'
    | '/api/public/softphone/case/get'
    | '/api/public/softphone/case/set'
    | '/api/public/softphone/case/debug-information/set'
    | '/api/public/softphone/case/event/set'
    | '/api/public/softphone/case/ivr-raw-text/set'
    | '/api/public/softphone/case/ivr-recognized/set'
    | '/api/public/softphone/case/phase/set'
  id:
    | '__root__'
    | '/'
    | '/admins'
    | '/softphone'
    | '/admins/analytics'
    | '/admins/developer-information'
    | '/admins/users'
    | '/api/health'
    | '/softphone/$scenarioId'
    | '/admins/scenarios/$scenarioId'
    | '/admins/scenarios/new'
    | '/api/auth/$'
    | '/api/softphone/acs-token'
    | '/api/softphone/bootstrap'
    | '/api/softphone/case'
    | '/api/softphone/events'
    | '/api/softphone/external-endpoints'
    | '/api/softphone/unlock'
    | '/admins/scenarios/'
    | '/api/softphone/case/debug-information'
    | '/api/softphone/case/ivr-raw-text'
    | '/api/softphone/case/ivr-recognized'
    | '/api/softphone/case/set'
    | '/api/softphone/scenario/$scenarioId'
    | '/api/public/softphone/case/get'
    | '/api/public/softphone/case/set'
    | '/api/public/softphone/case/debug-information/set'
    | '/api/public/softphone/case/event/set'
    | '/api/public/softphone/case/ivr-raw-text/set'
    | '/api/public/softphone/case/ivr-recognized/set'
    | '/api/public/softphone/case/phase/set'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminsRoute: typeof AdminsRouteWithChildren
  SoftphoneRoute: typeof SoftphoneRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiSoftphoneAcsTokenRoute: typeof ApiSoftphoneAcsTokenRoute
  ApiSoftphoneBootstrapRoute: typeof ApiSoftphoneBootstrapRoute
  ApiSoftphoneCaseRoute: typeof ApiSoftphoneCaseRouteWithChildren
  ApiSoftphoneEventsRoute: typeof ApiSoftphoneEventsRoute
  ApiSoftphoneExternalEndpointsRoute: typeof ApiSoftphoneExternalEndpointsRoute
  ApiSoftphoneUnlockRoute: typeof ApiSoftphoneUnlockRoute
  ApiSoftphoneScenarioScenarioIdRoute: typeof ApiSoftphoneScenarioScenarioIdRoute
  ApiPublicSoftphoneCaseGetRoute: typeof ApiPublicSoftphoneCaseGetRoute
  ApiPublicSoftphoneCaseSetRoute: typeof ApiPublicSoftphoneCaseSetRoute
  ApiPublicSoftphoneCaseDebugInformationSetRoute: typeof ApiPublicSoftphoneCaseDebugInformationSetRoute
  ApiPublicSoftphoneCaseEventSetRoute: typeof ApiPublicSoftphoneCaseEventSetRoute
  ApiPublicSoftphoneCaseIvrRawTextSetRoute: typeof ApiPublicSoftphoneCaseIvrRawTextSetRoute
  ApiPublicSoftphoneCaseIvrRecognizedSetRoute: typeof ApiPublicSoftphoneCaseIvrRecognizedSetRoute
  ApiPublicSoftphoneCasePhaseSetRoute: typeof ApiPublicSoftphoneCasePhaseSetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/softphone': {
      id: '/softphone'
      path: '/softphone'
      fullPath: '/softphone'
      preLoaderRoute: typeof SoftphoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admins': {
      id: '/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/softphone/$scenarioId': {
      id: '/softphone/$scenarioId'
      path: '/$scenarioId'
      fullPath: '/softphone/$scenarioId'
      preLoaderRoute: typeof SoftphoneScenarioIdRouteImport
      parentRoute: typeof SoftphoneRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admins/users': {
      id: '/admins/users'
      path: '/users'
      fullPath: '/admins/users'
      preLoaderRoute: typeof AdminsUsersRouteImport
      parentRoute: typeof AdminsRoute
    }
    '/admins/developer-information': {
      id: '/admins/developer-information'
      path: '/developer-information'
      fullPath: '/admins/developer-information'
      preLoaderRoute: typeof AdminsDeveloperInformationRouteImport
      parentRoute: typeof AdminsRoute
    }
    '/admins/analytics': {
      id: '/admins/analytics'
      path: '/analytics'
      fullPath: '/admins/analytics'
      preLoaderRoute: typeof AdminsAnalyticsRouteImport
      parentRoute: typeof AdminsRoute
    }
    '/admins/scenarios/': {
      id: '/admins/scenarios/'
      path: '/scenarios'
      fullPath: '/admins/scenarios/'
      preLoaderRoute: typeof AdminsScenariosIndexRouteImport
      parentRoute: typeof AdminsRoute
    }
    '/api/softphone/unlock': {
      id: '/api/softphone/unlock'
      path: '/api/softphone/unlock'
      fullPath: '/api/softphone/unlock'
      preLoaderRoute: typeof ApiSoftphoneUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/softphone/external-endpoints': {
      id: '/api/softphone/external-endpoints'
      path: '/api/softphone/external-endpoints'
      fullPath: '/api/softphone/external-endpoints'
      preLoaderRoute: typeof ApiSoftphoneExternalEndpointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/softphone/events': {
      id: '/api/softphone/events'
      path: '/api/softphone/events'
      fullPath: '/api/softphone/events'
      preLoaderRoute: typeof ApiSoftphoneEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/softphone/case': {
      id: '/api/softphone/case'
      path: '/api/softphone/case'
      fullPath: '/api/softphone/case'
      preLoaderRoute: typeof ApiSoftphoneCaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/softphone/bootstrap': {
      id: '/api/softphone/bootstrap'
      path: '/api/softphone/bootstrap'
      fullPath: '/api/softphone/bootstrap'
      preLoaderRoute: typeof ApiSoftphoneBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/softphone/acs-token': {
      id: '/api/softphone/acs-token'
      path: '/api/softphone/acs-token'
      fullPath: '/api/softphone/acs-token'
      preLoaderRoute: typeof ApiSoftphoneAcsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admins/scenarios/new': {
      id: '/admins/scenarios/new'
      path: '/scenarios/new'
      fullPath: '/admins/scenarios/new'
      preLoaderRoute: typeof AdminsScenariosNewRouteImport
      parentRoute: typeof AdminsRoute
    }
    '/admins/scenarios/$scenarioId': {
      id: '/admins/scenarios/$scenarioId'
      path: '/scenarios/$scenarioId'
      fullPath: '/admins/scenarios/$scenarioId'
      preLoaderRoute: typeof AdminsScenariosScenarioIdRouteImport
      parentRoute: typeof AdminsRoute
    }
    '/api/softphone/scenario/$scenarioId': {
      id: '/api/softphone/scenario/$scenarioId'
      path: '/api/softphone/scenario/$scenarioId'
      fullPath: '/api/softphone/scenario/$scenarioId'
      preLoaderRoute: typeof ApiSoftphoneScenarioScenarioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/softphone/case/set': {
      id: '/api/softphone/case/set'
      path: '/set'
      fullPath: '/api/softphone/case/set'
      preLoaderRoute: typeof ApiSoftphoneCaseSetRouteImport
      parentRoute: typeof ApiSoftphoneCaseRoute
    }
    '/api/softphone/case/ivr-recognized': {
      id: '/api/softphone/case/ivr-recognized'
      path: '/ivr-recognized'
      fullPath: '/api/softphone/case/ivr-recognized'
      preLoaderRoute: typeof ApiSoftphoneCaseIvrRecognizedRouteImport
      parentRoute: typeof ApiSoftphoneCaseRoute
    }
    '/api/softphone/case/ivr-raw-text': {
      id: '/api/softphone/case/ivr-raw-text'
      path: '/ivr-raw-text'
      fullPath: '/api/softphone/case/ivr-raw-text'
      preLoaderRoute: typeof ApiSoftphoneCaseIvrRawTextRouteImport
      parentRoute: typeof ApiSoftphoneCaseRoute
    }
    '/api/softphone/case/debug-information': {
      id: '/api/softphone/case/debug-information'
      path: '/debug-information'
      fullPath: '/api/softphone/case/debug-information'
      preLoaderRoute: typeof ApiSoftphoneCaseDebugInformationRouteImport
      parentRoute: typeof ApiSoftphoneCaseRoute
    }
    '/api/public/softphone/case/set': {
      id: '/api/public/softphone/case/set'
      path: '/api/public/softphone/case/set'
      fullPath: '/api/public/softphone/case/set'
      preLoaderRoute: typeof ApiPublicSoftphoneCaseSetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/softphone/case/get': {
      id: '/api/public/softphone/case/get'
      path: '/api/public/softphone/case/get'
      fullPath: '/api/public/softphone/case/get'
      preLoaderRoute: typeof ApiPublicSoftphoneCaseGetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/softphone/case/phase/set': {
      id: '/api/public/softphone/case/phase/set'
      path: '/api/public/softphone/case/phase/set'
      fullPath: '/api/public/softphone/case/phase/set'
      preLoaderRoute: typeof ApiPublicSoftphoneCasePhaseSetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/softphone/case/ivr-recognized/set': {
      id: '/api/public/softphone/case/ivr-recognized/set'
      path: '/api/public/softphone/case/ivr-recognized/set'
      fullPath: '/api/public/softphone/case/ivr-recognized/set'
      preLoaderRoute: typeof ApiPublicSoftphoneCaseIvrRecognizedSetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/softphone/case/ivr-raw-text/set': {
      id: '/api/public/softphone/case/ivr-raw-text/set'
      path: '/api/public/softphone/case/ivr-raw-text/set'
      fullPath: '/api/public/softphone/case/ivr-raw-text/set'
      preLoaderRoute: typeof ApiPublicSoftphoneCaseIvrRawTextSetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/softphone/case/event/set': {
      id: '/api/public/softphone/case/event/set'
      path: '/api/public/softphone/case/event/set'
      fullPath: '/api/public/softphone/case/event/set'
      preLoaderRoute: typeof ApiPublicSoftphoneCaseEventSetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/softphone/case/debug-information/set': {
      id: '/api/public/softphone/case/debug-information/set'
      path: '/api/public/softphone/case/debug-information/set'
      fullPath: '/api/public/softphone/case/debug-information/set'
      preLoaderRoute: typeof ApiPublicSoftphoneCaseDebugInformationSetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminsRouteChildren {
  AdminsAnalyticsRoute: typeof AdminsAnalyticsRoute
  AdminsDeveloperInformationRoute: typeof AdminsDeveloperInformationRoute
  AdminsUsersRoute: typeof AdminsUsersRoute
  AdminsScenariosScenarioIdRoute: typeof AdminsScenariosScenarioIdRoute
  AdminsScenariosNewRoute: typeof AdminsScenariosNewRoute
  AdminsScenariosIndexRoute: typeof AdminsScenariosIndexRoute
}

const AdminsRouteChildren: AdminsRouteChildren = {
  AdminsAnalyticsRoute: AdminsAnalyticsRoute,
  AdminsDeveloperInformationRoute: AdminsDeveloperInformationRoute,
  AdminsUsersRoute: AdminsUsersRoute,
  AdminsScenariosScenarioIdRoute: AdminsScenariosScenarioIdRoute,
  AdminsScenariosNewRoute: AdminsScenariosNewRoute,
  AdminsScenariosIndexRoute: AdminsScenariosIndexRoute,
}

const AdminsRouteWithChildren =
  AdminsRoute._addFileChildren(AdminsRouteChildren)

interface SoftphoneRouteChildren {
  SoftphoneScenarioIdRoute: typeof SoftphoneScenarioIdRoute
}

const SoftphoneRouteChildren: SoftphoneRouteChildren = {
  SoftphoneScenarioIdRoute: SoftphoneScenarioIdRoute,
}

const SoftphoneRouteWithChildren = SoftphoneRoute._addFileChildren(
  SoftphoneRouteChildren,
)

interface ApiSoftphoneCaseRouteChildren {
  ApiSoftphoneCaseDebugInformationRoute: typeof ApiSoftphoneCaseDebugInformationRoute
  ApiSoftphoneCaseIvrRawTextRoute: typeof ApiSoftphoneCaseIvrRawTextRoute
  ApiSoftphoneCaseIvrRecognizedRoute: typeof ApiSoftphoneCaseIvrRecognizedRoute
  ApiSoftphoneCaseSetRoute: typeof ApiSoftphoneCaseSetRoute
}

const ApiSoftphoneCaseRouteChildren: ApiSoftphoneCaseRouteChildren = {
  ApiSoftphoneCaseDebugInformationRoute: ApiSoftphoneCaseDebugInformationRoute,
  ApiSoftphoneCaseIvrRawTextRoute: ApiSoftphoneCaseIvrRawTextRoute,
  ApiSoftphoneCaseIvrRecognizedRoute: ApiSoftphoneCaseIvrRecognizedRoute,
  ApiSoftphoneCaseSetRoute: ApiSoftphoneCaseSetRoute,
}

const ApiSoftphoneCaseRouteWithChildren =
  ApiSoftphoneCaseRoute._addFileChildren(ApiSoftphoneCaseRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminsRoute: AdminsRouteWithChildren,
  SoftphoneRoute: SoftphoneRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSoftphoneAcsTokenRoute: ApiSoftphoneAcsTokenRoute,
  ApiSoftphoneBootstrapRoute: ApiSoftphoneBootstrapRoute,
  ApiSoftphoneCaseRoute: ApiSoftphoneCaseRouteWithChildren,
  ApiSoftphoneEventsRoute: ApiSoftphoneEventsRoute,
  ApiSoftphoneExternalEndpointsRoute: ApiSoftphoneExternalEndpointsRoute,
  ApiSoftphoneUnlockRoute: ApiSoftphoneUnlockRoute,
  ApiSoftphoneScenarioScenarioIdRoute: ApiSoftphoneScenarioScenarioIdRoute,
  ApiPublicSoftphoneCaseGetRoute: ApiPublicSoftphoneCaseGetRoute,
  ApiPublicSoftphoneCaseSetRoute: ApiPublicSoftphoneCaseSetRoute,
  ApiPublicSoftphoneCaseDebugInformationSetRoute:
    ApiPublicSoftphoneCaseDebugInformationSetRoute,
  ApiPublicSoftphoneCaseEventSetRoute: ApiPublicSoftphoneCaseEventSetRoute,
  ApiPublicSoftphoneCaseIvrRawTextSetRoute:
    ApiPublicSoftphoneCaseIvrRawTextSetRoute,
  ApiPublicSoftphoneCaseIvrRecognizedSetRoute:
    ApiPublicSoftphoneCaseIvrRecognizedSetRoute,
  ApiPublicSoftphoneCasePhaseSetRoute: ApiPublicSoftphoneCasePhaseSetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
